MINI = mini mini2 mini3 mini4 mini5 mini6 mini7 mini8 mini9 factorial condicionales vectores fibonacci funciones_vectores funciones
TEST = test0 test1
.PHONY: clean
clean:
	rm -rf *.asm *.o $(MINI) $(TEST)
